// רשימת מדינות: [קוד, עברית, אנגלית] — לבורר חיפוש בטופס המוצר
window.COUNTRIES = [
["IL","ישראל","Israel"],["US","ארצות הברית","United States"],["GB","בריטניה","United Kingdom"],
["DE","גרמניה","Germany"],["FR","צרפת","France"],["IT","איטליה","Italy"],["ES","ספרד","Spain"],
["NL","הולנד","Netherlands"],["BE","בלגיה","Belgium"],["CH","שווייץ","Switzerland"],
["AT","אוסטריה","Austria"],["SE","שוודיה","Sweden"],["NO","נורווגיה","Norway"],
["DK","דנמרק","Denmark"],["FI","פינלנד","Finland"],["IE","אירלנד","Ireland"],
["PT","פורטוגל","Portugal"],["GR","יוון","Greece"],["PL","פולין","Poland"],
["CZ","צ'כיה","Czechia"],["HU","הונגריה","Hungary"],["RO","רומניה","Romania"],
["BG","בולגריה","Bulgaria"],["HR","קרואטיה","Croatia"],["SK","סלובקיה","Slovakia"],
["SI","סלובניה","Slovenia"],["LT","ליטא","Lithuania"],["LV","לטביה","Latvia"],
["EE","אסטוניה","Estonia"],["RS","סרביה","Serbia"],["UA","אוקראינה","Ukraine"],
["RU","רוסיה","Russia"],["TR","טורקיה","Turkey"],["CY","קפריסין","Cyprus"],
["MT","מלטה","Malta"],["IS","איסלנד","Iceland"],["LU","לוקסמבורג","Luxembourg"],
["CA","קנדה","Canada"],["MX","מקסיקו","Mexico"],["BR","ברזיל","Brazil"],
["AR","ארגנטינה","Argentina"],["CL","צ'ילה","Chile"],["CO","קולומביה","Colombia"],
["PE","פרו","Peru"],["UY","אורוגוואי","Uruguay"],["VE","ונצואלה","Venezuela"],
["CN","סין","China"],["JP","יפן","Japan"],["KR","דרום קוריאה","South Korea"],
["IN","הודו","India"],["TH","תאילנד","Thailand"],["VN","וייטנאם","Vietnam"],
["SG","סינגפור","Singapore"],["MY","מלזיה","Malaysia"],["ID","אינדונזיה","Indonesia"],
["PH","פיליפינים","Philippines"],["TW","טאיוואן","Taiwan"],["HK","הונג קונג","Hong Kong"],
["AU","אוסטרליה","Australia"],["NZ","ניו זילנד","New Zealand"],
["AE","איחוד האמירויות","United Arab Emirates"],["SA","ערב הסעודית","Saudi Arabia"],
["QA","קטאר","Qatar"],["KW","כווית","Kuwait"],["JO","ירדן","Jordan"],
["EG","מצרים","Egypt"],["MA","מרוקו","Morocco"],["TN","תוניסיה","Tunisia"],
["ZA","דרום אפריקה","South Africa"],["NG","ניגריה","Nigeria"],["KE","קניה","Kenya"],
["ET","אתיופיה","Ethiopia"],["GH","גאנה","Ghana"],["IR","איראן","Iran"],
["IQ","עיראק","Iraq"],["PK","פקיסטן","Pakistan"],["BD","בנגלדש","Bangladesh"],
["LK","סרי לנקה","Sri Lanka"],["NP","נפאל","Nepal"],["KZ","קזחסטן","Kazakhstan"],
["UZ","אוזבקיסטן","Uzbekistan"],["GE","גאורגיה","Georgia"],["AM","ארמניה","Armenia"],
["AZ","אזרבייג'ן","Azerbaijan"],["BY","בלארוס","Belarus"],["MD","מולדובה","Moldova"],
["AL","אלבניה","Albania"],["BA","בוסניה","Bosnia and Herzegovina"],
["MK","מקדוניה","North Macedonia"],["ME","מונטנגרו","Montenegro"],
["CR","קוסטה ריקה","Costa Rica"],["PA","פנמה","Panama"],["GT","גואטמלה","Guatemala"],
["DO","הרפובליקה הדומיניקנית","Dominican Republic"],["CU","קובה","Cuba"],
["EC","אקוודור","Ecuador"],["BO","בוליביה","Bolivia"],["PY","פרגוואי","Paraguay"]
];
